"""upd book and image

Revision ID: 6b02d1bb305b
Revises: b319d0905b30
Create Date: 2022-06-21 16:00:40.416896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b02d1bb305b'
down_revision = 'b319d0905b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('rating_sum', sa.INTEGER(), nullable=False))
    op.add_column('books', sa.Column('rating_num', sa.INTEGER(), nullable=False))
    op.add_column('images', sa.Column('object_type', sa.String(length=100), nullable=True))
    op.add_column('images', sa.Column('object_id', sa.INTEGER(), nullable=True))
    op.add_column('images', sa.Column('active', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'active')
    op.drop_column('images', 'object_id')
    op.drop_column('images', 'object_type')
    op.drop_column('books', 'rating_num')
    op.drop_column('books', 'rating_sum')
    # ### end Alembic commands ###
